// Automatically generated by astro-icon
// f5a57e51fb24886e755a7cbcf139fd6e3c3af26675b5318bbe5ced067351aa48

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fa6-brands:x-twitter"
		| "fa6-brands:github"
		| "fa6-brands:instagram"
		| "fa6-brands:linkedin-in"
		| "fa6-solid:rss"
		| "fa6-solid:circle-half-stroke"
		| "tabler:mail-filled";
}