
# Site settings
name: francescodelprato.github.io
title: Francesco Del Prato
tagline: Personal webpage of Francesco Del Prato - economics
description: PhD candidate in Business Economics between IMT and KU Leuven
#repo: 
url: https://francescodelprato.github.io
baseurl: /
google_analytics: G-CB0P1912PV
#google-site-verification: EjDn9NB75Ybc73Rp6H3LzGkSFajoB4_PGmSHZUPYT3o

# Personal info
author: Francesco Del Prato
first_name: Francesco
last_name: Del Prato
#university: 
#department: 
#address: 
#office: 
email: francesco.delprato@kuleuven.be

# Markdown
markdown: kramdown

# SEO
plugins:
  - jekyll-seo-tag
